import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { trackEvent } from '../../utils/analytics'
import PhoneMockup from '../ui/PhoneMockup'

export default function DemoSection() {
  const features = [
    'Clothing analysis powered by Gemini 2.5 Flash',
    'Size recommendations with 85-95% confidence scores',
    'Virtual try-on images generated by Replicate',
    'Outfit and style suggestions tailored to you',
    'Your body data stored securely in the cloud',
  ]

  return (
    <section className="demo-section" id="demo">
      <div className="container">
        <div className="demo-container">
          <div className="demo-content" data-scroll-reveal="blur-up">
            <div className="section-eyebrow">Live Demo</div>
            <h2>See Loomeé in Action</h2>
            <p>
              Upload a photo, pick something you like, and get a full fit report
              with a virtual try-on in under five seconds.
            </p>

            <ul className="demo-features-list">
              {features.map((f, i) => (
                <li key={i} className="demo-feature-item">
                  <div className="check-icon" aria-hidden="true"><CheckCircle2 size={14} /></div>
                  {f}
                </li>
              ))}
            </ul>

            <a
              href="#cta"
              className="btn-primary btn-large"
              onClick={() => trackEvent('cta_click', { location: 'demo' })}
            >
              Try It Now <ArrowRight size={18} />
            </a>
          </div>

          <div className="demo-visual" aria-hidden="true" data-scroll-reveal="blur-up" style={{ '--reveal-delay': '150ms' }}>
            <PhoneMockup />
          </div>
        </div>
      </div>
    </section>
  )
}
