import LegalPage from './LegalPage'

export default function TermsOfServicePage() {
  return (
    <LegalPage title="Terms of Service">
      <p className="legal-updated">Last updated: 1 March 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using Loomeé VTO (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>

      <h2>2. Description of Service</h2>
      <p>Loomeé VTO is an AI-powered virtual fitting room application that analyses user-submitted body photos to generate personalised size recommendations and virtual outfit previews. The Service is powered by Google Gemini AI and is available on iOS, Android, and via our website.</p>

      <h2>3. Eligibility</h2>
      <p>You must be at least 13 years of age to use this Service. By using Loomeé VTO, you represent that you meet this age requirement. Users under 18 should have parental or guardian consent.</p>

      <h2>4. User Accounts</h2>
      <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorised use of your account at loomeevto@gmail.com.</p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to use the Service to upload content that is unlawful, harmful, or violates the rights of others; attempt to reverse-engineer, hack, or disrupt the Service; use automated scripts or bots to access the Service; or misrepresent your identity or affiliation.</p>

      <h2>6. AI Recommendations Disclaimer</h2>
      <p>Size recommendations and virtual try-on previews generated by Loomeé VTO are provided for guidance only and are based on AI analysis of user-submitted photos. Results may vary depending on photo quality, lighting, and individual body characteristics. We do not guarantee the accuracy of any recommendation. Final purchasing decisions remain the sole responsibility of the user.</p>

      <h2>7. Intellectual Property</h2>
      <p>All content, branding, software, and technology comprising the Loomeé VTO Service are the exclusive property of Loomeé VTO and are protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written permission.</p>

      <h2>8. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, Loomeé VTO shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Service. Our total liability to you for any claims arising from these Terms shall not exceed the amount you paid us in the 12 months preceding the claim.</p>

      <h2>9. Termination</h2>
      <p>We reserve the right to suspend or terminate your access to the Service at our discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.</p>

      <h2>10. Governing Law</h2>
      <p>These Terms are governed by applicable law. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the relevant courts.</p>

      <h2>11. Changes to Terms</h2>
      <p>We may modify these Terms at any time. We will provide notice of significant changes. Your continued use of the Service following notice of changes constitutes acceptance of the updated Terms.</p>

      <h2>12. Contact</h2>
      <p>For questions about these Terms, contact us at <a href="mailto:loomeevto@gmail.com">loomeevto@gmail.com</a>.</p>
    </LegalPage>
  )
}
